experiment_name: "ablation_hqae_strong_d1_z_axis"
data_dir: "/content/local_spectra_data/processed_spectrograms"
save_dir: "/content/drive/MyDrive/spectra-cq-data/checkpoints/quantum/strong_d1"
seeds: [42, 100, 2026]
epochs: 15
batch_size: 32
learning_rate: 0.001
train_split: 0.8
latent_dim: 8
n_quantum_layers: 1
topology: "strong"